# Generated by Django 3.0.5 on 2020-05-01 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfie',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
