# Generated by Django 3.0.5 on 2020-05-01 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20200501_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='selfie',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
